language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
node_js:
  - '8'
script:
  - echo "Running CI script(s)"
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
